services:
  postgres:
    image: postgres
    container_name: wave-registration_db
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registration_db
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local