server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    #security configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${OAUTH_FACEBOOK_CLIENT_ID}
            client-secret: ${OAUTH_FACEBOOK_CLIENT_SECRET}
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri=${spring:
            security:
              oauth2:
                resourceserver:
          issuer-uri}/protocol/openid-connect/certs:
          #jwt config
        auth:
         converter:
          resource-id=WaveClient:
          principal-attribute=principal_username:
# less secure apps and app passwords don't work and will get disabled on 30th september 2024
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SMTP_USERNAME}
#    password: ${SMTP_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
